name: Run Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npx playwright install-deps
          npx playwright install
          npm install
      - name: Run tests
        run: npm test
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test-artifacts
          path: |
            tests/
            test-results/
