name: Run Tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          time npm install
          time npx playwright install-deps
          time npx playwright install
      - name: Run tests
        run: npm test
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test-artifacts
          path: |
            tests/
            test-results/
